<?php

namespace BetaGT\UserAclManager\Repositories;

use BetaGT\UserAclManager\Presenters\PermissionPresenter;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use BetaGT\UserAclManager\Repositories\PermissionRepository;
use BetaGT\UserAclManager\Models\Permission;
use BetaGT\UserAclManager\Validators\PermissionValidator;

/**
 * Class PermissionRepositoryEloquent
 * @package namespace BetaGT\UserAclManager\Repositories;
 */
class PermissionRepositoryEloquent extends BaseRepository implements PermissionRepository
{

    protected $fieldSearchable = [
        'name'=>'like'
    ];

    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Permission::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }

    public function presenter()
    {
        return PermissionPresenter::class; // TODO: Change the autogenerated stub
    }
}
